services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: secretmanager
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped


  openbao:
    image: openbao/openbao:2.4.1
    container_name: openbao
    ports:
      - "8200:8200"
    environment:
      OPENBAO_ROOT_TOKEN: "your-root-token"
    volumes:
      - openbao_data:/openbao/data


  backend:
    build:
      context: ./backend
    container_name: backend
    environment:
      DATABASE_URL: postgres://admin:${POSTGRES_PASSWORD}@postgres:5432/secretmanager
      OPENBAO_URL: http://openbao:8080
      OPENBAO_TOKEN: ${OPENBAO_ROOT_TOKEN}
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - openbao
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8000 --reload
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data:
