vversion: "3.8"

services:
version: "3.9"

services:
  openbao:
    image: openbao/openbao:2.4.1
    container_name: openbao
    ports:
      - "8080:8080"
    environment:
      OPENBAO_ROOT_TOKEN: "root-token"  # укажи свой
    volumes:
      - openbao_data:/openbao/data

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres-password"  # укажи свой
      POSTGRES_DB: "secretmanager"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    depends_on:
      - openbao
      - postgres
    environment:
      DATABASE_URL: "postgresql://postgres:postgres-password@postgres:5432/secretmanager"
      OPENBAO_URL: "http://openbao:8080"
      OPENBAO_ROOT_TOKEN: "root-token"

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - backend

volumes:
  openbao_data:
  postgres_data: