vversion: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/secrets
      FERNET_KEY: "YOUR_KEY_HERE"
      KEYCLOAK_URL: "http://keycloak:8080"
      OPENBAO_URL: "http://openbao:5000"
    depends_on:
      - db
      - keycloak
      - openbao

  frontend:
    build: ./frontend
    ports:
      - "3000:80"  # порт 3000 для браузера, внутри Nginx 80
    depends_on:
      - backend

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: secrets
    ports:
      - "5432:5432"

  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev
    ports:
      - "8080:8080"

  openbao:
    image: openbao/openbao:latest
    ports:
      - "5000:5000"
