vversion: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
  version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      FERNET_KEY: ${FERNET_KEY}
      KEYCLOAK_URL: ${KEYCLOAK_URL}
      OPENBAO_URL: ${OPENBAO_URL}
    depends_on:
      - db
      - keycloak
      - openbao

frontend:
  build:
    context: ./nginx
  ports:
    - "3000:80"
  depends_on:
    - backend

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: secrets
    ports:
      - "5432:5432"

  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev
    ports:
      - "8080:8080"

  openbao:
    image: openbao/openbao:latest
    ports:
      - "5000:5000"
